### ISSUE TITLE
OIDC example

### ISSUE THREAD

**Issue by mihaigalos** [myOmikron/actix-toolbox#2]
Hi,

Cool stuff.
Did you already test the OIDC part and can provide a usage example?

**Comment by myOmikron** [comment]
Hello there,

yeah, I have a few projects that are using the oidc module. As @gammelalf is the author of this part, he will provide an example

**Comment by gammelalf** [comment]
Hi,

glad you like it.
I just pushed an example (2b2d695), let me know if anything is unclear.

The API is still quite clunky and needs polish. We just pushed it to work for our projects.
Feel free to leave feedback how you'd expect the API to be.
